version: '2'
services:

# apache based images

  # A base image for apache - based moodle builds
  moodle_apache_base:
      build:
        context: .
        dockerfile: dockerfiles/apache/Dockerfile_base
      image: ellakcy/moodle:apache_base

  # Mysql running variant
  moodle_mysql_db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_mysql:
    build:
      context: .
      dockerfile: dockerfiles/apache/Dockerfile_mysql
    image: ellakcy/moodle:mysql_maria_apache
    links:
      - "moodle_mysql_db:moodle_db"
      - "moodle_apache_base"
    ports:
      - "6080:80"
    environment:
      MOODLE_DB_HOST: "moodle_mysql_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "http://0.0.0.0:6080"

  # postgresql running variant
  moodle_psql_db:
    image: postgres
    environment:
      POSTGRES_DB: "${MOODLE_DB_NAME}"
      POSTGRES_USER: '${MOODLE_MYSQL_USER}'
      POSTGRES_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_psql:
    build:
      context: .
      dockerfile: dockerfiles/apache/Dockerfile_postgrtesql
    image: ellakcy/moodle:postgresql_apache
    links:
      - "moodle_psql_db:moodle_db"
      - "moodle_apache_base"
    ports:
      - "6082:80"
    environment:
      MOODLE_DB_HOST: "moodle_psql_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "http://0.0.0.0:6082"

  # Testing mariadb support
  moodle_maria_db:
      image: mariadb
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_ONETIME_PASSWORD: "yes"
        MYSQL_DATABASE: "${MOODLE_DB_NAME}"
        MYSQL_USER: '${MOODLE_MYSQL_USER}'
        MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_maria:
      image: ellakcy/moodle:mysql_maria_apache
      links:
        - "moodle_mysql"
        - "moodle_maria_db:moodle_db"
      ports:
        - "6081:80"
      environment:
        MOODLE_DB_HOST: "moodle_maria_db"
        MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
        MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
        MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
        MOODLE_ADMIN: "${MOODLE_ADMIN}"
        MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
        MOODLE_URL: "http://0.0.0.0:6081"

#Alpine fpm based images
  #Basic alpine fpm image
  moodle_alpine_fpm_base:
    build:
      context: .
      dockerfile: dockerfiles/fpm_alpine/Dockerfile_base
    image: ellakcy/moodle:alpine_fpm_base

  #Mysql variant

  nginx_mysql:
   image: nginx:alpine
   ports:
     - "7070:7070"
   volumes:
     - './conf/nginx/nginx_mysql.conf:/etc/nginx/nginx.conf:ro'
   links:
     - 'moodle_alpine_fpm_mysql'
   volumes_from:
     - 'moodle_alpine_fpm_mysql'

  moodle_mysql_alpine_db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_mysql:
    build:
      context: .
      dockerfile: dockerfiles/fpm_alpine/Dockerfile_mysql
    image: ellakcy/moodle:mysql_maria_fpm_alpine
    links:
      - "moodle_mysql_alpine_db:moodle_db"
      - "moodle_alpine_fpm_base"
    environment:
      MOODLE_DB_HOST: "moodle_mysql_alpine_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "http://0.0.0.0:7070"

  #Mariadb for demÎ¿nstration
  nginx_maria:
   image: nginx:alpine
   ports:
     - "7071:7071"
   volumes:
     - './conf/nginx/nginx_mariadb.conf:/etc/nginx/nginx.conf:ro'
   links:
     - 'moodle_alpine_fpm_mariadb'
   volumes_from:
     - 'moodle_alpine_fpm_mariadb'

  moodle_mariadb_alpine_db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_mariadb:
    image: ellakcy/moodle:mysql_maria_fpm_alpine
    links:
      - "moodle_mariadb_alpine_db:moodle_db"
      - "moodle_alpine_fpm_base"
    environment:
      MOODLE_DB_HOST: "moodle_mariadb_alpine_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "http://0.0.0.0:7071"

    #Postgresql
  nginx_pgsql:
      image: nginx:alpine
      ports:
        - "7072:7072"
      volumes:
        - './conf/nginx/nginx_psql.conf:/etc/nginx/nginx.conf:ro'
      links:
        - 'moodle_alpine_fpm_psql'
      volumes_from:
        - 'moodle_alpine_fpm_psql'

  moodle_psql_alpine_db:
      image: postgres
      environment:
        POSTGRES_DB: "${MOODLE_DB_NAME}"
        POSTGRES_USER: '${MOODLE_MYSQL_USER}'
        POSTGRES_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_psql:
      build:
        context: .
        dockerfile: dockerfiles/fpm_alpine/Dockerfile_postgresql
      image: ellakcy/moodle:postgresql_fpm_alpine
      links:
        - "moodle_psql_alpine_db:moodle_db"
        - "moodle_alpine_fpm_base"
      environment:
        MOODLE_DB_HOST: "moodle_psql_alpine_db"
        MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
        MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
        MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
        MOODLE_ADMIN: "${MOODLE_ADMIN}"
        MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
        MOODLE_URL: "http://0.0.0.0:7072"

#################################################################################################################
####################################### SSL REVERSE PROXY TESTING ###############################################
#################################################################################################################

# Reverse Proxy testing
  nginx_reverse:
    image: nginx:alpine
    ports:
      - "6440:6440"
      - "6441:6441"
      - "6442:6442"
      - "6444:6444"
      - "6445:6445"
      - "6446:6446"
    links:
      - 'moodle_mysql_reverse'
      - 'moodle_maria_reverse'
      - 'moodle_psql_reverse'
      - 'nginx_mysql_reverse'
      - 'nginx_maria_reverse'
      - 'nginx_pgsql_reverse'
    volumes:
      - './conf/nginx/nginx_ssl_reverse.conf:/etc/nginx/nginx.conf:ro'
      - './conf/certs:/etc/nginx/certs:ro'

##################### Images for test ##########################################


############# Apache based variants ############################################

  moodle_mysql_db_reverse:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_mysql_reverse:
    image: ellakcy/moodle:mysql_maria_apache
    links:
      - "moodle_mysql_db_reverse:moodle_db"
    environment:
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "https://0.0.0.0:6440"
      MOODLE_REVERSE_LB: "true"
      MOODLE_SSL: "true"

  # postgresql running variant
  moodle_psql_db_reverse:
    image: postgres
    environment:
      POSTGRES_DB: "${MOODLE_DB_NAME}"
      POSTGRES_USER: '${MOODLE_MYSQL_USER}'
      POSTGRES_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_psql_reverse:
    build:
      context: .
      dockerfile: dockerfiles/apache/Dockerfile_postgrtesql
    image: ellakcy/moodle:postgresql_apache
    links:
      - "moodle_psql_db_reverse:moodle_db"
      - "moodle_apache_base"
    environment:
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "https://0.0.0.0:6441"
      MOODLE_REVERSE_LB: "true"
      MOODLE_SSL: "true"

  # Testing mariadb support
  moodle_maria_db_reverse:
      image: mariadb
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_ONETIME_PASSWORD: "yes"
        MYSQL_DATABASE: "${MOODLE_DB_NAME}"
        MYSQL_USER: '${MOODLE_MYSQL_USER}'
        MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_maria_reverse:
      image: ellakcy/moodle:mysql_maria_apache
      links:
        - "moodle_mysql_reverse"
        - "moodle_maria_db_reverse:moodle_db"
      environment:
        MOODLE_DB_HOST: "moodle_db"
        MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
        MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
        MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
        MOODLE_ADMIN: "${MOODLE_ADMIN}"
        MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
        MOODLE_URL: "http://0.0.0.0:6442"
        MOODLE_REVERSE_LB: "true"
        MOODLE_SSL: "true"

########################### Alpine fpm based images ############################

  #Mysql variant
  nginx_mysql_reverse:
   image: nginx:alpine
   ports:
     - "6070:6070"
   volumes:
     - './conf/nginx/nginx_mysql.conf:/etc/nginx/nginx.conf:ro'
   links:
     - 'moodle_alpine_fpm_mysql'
   volumes_from:
     - 'moodle_alpine_fpm_mysql'

  moodle_mysql_alpine_db_reverse:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_mysql_reverse:
    build:
      context: .
      dockerfile: dockerfiles/fpm_alpine/Dockerfile_mysql
    image: ellakcy/moodle:mysql_maria_fpm_alpine
    links:
      - "moodle_mysql_alpine_db_reverse:moodle_db"
      - "moodle_alpine_fpm_base"
    environment:
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "https://0.0.0.0:6445"
      MOODLE_REVERSE_LB: "true"
      MOODLE_SSL: "true"

  #Mariadb for dempnstration
  nginx_maria_reverse:
   image: nginx:alpine
   ports:
     - "6071:6071"
   volumes:
     - './conf/nginx/nginx_mariadb.conf:/etc/nginx/nginx.conf:ro'
   links:
     - 'moodle_alpine_fpm_mariadb_reverse'
   volumes_from:
     - 'moodle_alpine_fpm_mariadb_reverse'

  moodle_mariadb_alpine_db_reverse:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_mariadb_reverse:
    image: ellakcy/moodle:mysql_maria_fpm_alpine
    links:
      - "moodle_mariadb_alpine_db_reverse:moodle_db"
      - "moodle_alpine_fpm_base"
    environment:
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "http://0.0.0.0:6444"
      MOODLE_REVERSE_LB: "true"
      MOODLE_SSL: "true"

  #Postgresql
  nginx_pgsql_reverse:
      image: nginx:alpine
      ports:
        - "6072:6072"
      volumes:
        - './conf/nginx/nginx_psql.conf:/etc/nginx/nginx.conf:ro'
      links:
        - 'moodle_alpine_fpm_psql'
      volumes_from:
        - 'moodle_alpine_fpm_psql'

  moodle_psql_alpine_db_reverse:
      image: postgres
      environment:
        POSTGRES_DB: "${MOODLE_DB_NAME}"
        POSTGRES_USER: '${MOODLE_MYSQL_USER}'
        POSTGRES_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_psql_reverse:
      build:
        context: .
        dockerfile: dockerfiles/fpm_alpine/Dockerfile_postgresql
      image: ellakcy/moodle:postgresql_fpm_alpine
      links:
        - "moodle_psql_alpine_db_reverse:moodle_db"
        - "moodle_alpine_fpm_base"
      environment:
        MOODLE_DB_HOST: "moodle_db"
        MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
        MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
        MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
        MOODLE_ADMIN: "${MOODLE_ADMIN}"
        MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
        MOODLE_URL: "http://0.0.0.0:6446"
        MOODLE_REVERSE_LB: "true"
        MOODLE_SSL: "true"
