# Dockerfile for moodle instance.

FROM  php:7.1-fpm-alpine
MAINTAINER Dimitrios Desyllas <pcmagas@disroot.org>
#Original Maintainer Jon Auer <jda@coldshore.com>

# Replace for later version
ARG VERSION=36

VOLUME ["/var/moodledata"]
VOLUME ["/var/www/html"]
EXPOSE 9000

# Let the container know that there is no tty
ENV \
		MOODLE_URL http://0.0.0.0 \
    MOODLE_ADMIN admin \
    MOODLE_ADMIN_PASSWORD Admin~1234 \
    MOODLE_ADMIN_EMAIL admin@example.com \
    MOODLE_DB_TYPE 'mysqli' \
    MOODLE_DB_HOST '' \
    MOODLE_DB_PASSWORD '' \
    MOODLE_DB_USER '' \
    MOODLE_DB_NAME '' \
    MOODLE_DB_PORT '3306'

# Installing php and external tools
RUN \
		apk add --update curl bash rsync unzip netcat-openbsd libxml2-dev icu-dev libmcrypt-dev libpng-dev libjpeg-turbo-dev autoconf && \
 		docker-php-ext-install xmlrpc && \
		docker-php-ext-install mbstring && \
		docker-php-ext-install zip && \
		docker-php-ext-install intl && \
 		docker-php-ext-install soap && \
 		docker-php-ext-install mcrypt && \
		docker-php-ext-install gd && \
		docker-php-ext-install opcache && \
		echo "Installing moodle" && \
		curl https://download.moodle.org/download.php/direct/stable${VERSION}/moodle-latest-${VERSION}.zip -o /tmp/moodle-latest.zip  && \
		rm -rf /var/www/html/index.html && \
		cd /tmp &&	unzip /tmp/moodle-latest.zip && cd / \
		mkdir -p /usr/src/moodle && \
		mv /tmp/moodle /usr/src/ && \
		chown www-data:www-data -R /usr/src/moodle && \
		apk del unzip curl gcc g++ && \
    rm -rf /var/cache/apk/*

COPY ./scripts/file-upload.ini /usr/local/etc/php/conf.d/file-upload.ini

# Install Redis 4.1 support
RUN apk add --update curl bash rsync unzip netcat-openbsd libxml2-dev icu-dev libmcrypt-dev libpng-dev libjpeg-turbo-dev autoconf gcc musl-dev make && \
    pecl install redis-4.1.1 \
    && docker-php-ext-enable redis \
    && apk del autoconf gcc musl-dev make \
    && rm -rf /var/cache/apk/*

# Install Memcached support
RUN apk add --update autoconf file g++ gcc libc-dev make pkgconf re2c zlib-dev libmemcached-dev git libmemcached-libs zlib cyrus-sasl-dev \
    && yes yes | pecl install memcached \
    && docker-php-ext-enable memcached \
    && apk del autoconf file g++ gcc libc-dev make pkgconf re2c zlib-dev libmemcached-dev libmemcached-libs zlib cyrus-sasl-dev && rm -rf /var/cache/apk/*

# Install MooSh
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    /usr/local/bin/composer self-update && \
    git clone git://github.com/tmuras/moosh.git /usr/local/moosh-online && \
    cd /usr/local/moosh-online && composer install && \
    ln -s /usr/local/moosh-online/moosh.php /usr/local/bin/moosh

RUN echo "* * * * * /usr/local/bin/php  /var/www/html/admin/cli/cron.php >/dev/null" > /etc/periodic/15min/moodle-cron && \
    chmod a+x /etc/periodic/15min/moodle-cron

CMD /usr/sbin/crond

COPY ./scripts/moodle-config-fpm.php /usr/src/moodle/config.php

ENTRYPOINT [exit]
