# Dockerfile for moodle instance.
# Forked from Jonathan Hardison's <jmh@jonathanhardison.com> docker version. https://github.com/jmhardison/docker-moodle

FROM  php:7.1-apache
MAINTAINER Dimitrios Desyllas <pcmagas@disroot.org>
#Original Maintainer Jon Auer <jda@coldshore.com>

# Replace for later version
ARG VERSION=35

VOLUME ["/var/moodledata"]
EXPOSE 80

# Let the container know that there is no tty
ENV DEBIAN_FRONTEND noninteractive \
		MOODLE_URL http://0.0.0.0 \
    MOODLE_ADMIN admin \
    MOODLE_ADMIN_PASSWORD Admin~1234 \
    MOODLE_ADMIN_EMAIL admin@example.com \
    MOODLE_DB_TYPE 'mysqli' \
    MOODLE_DB_HOST '' \
    MOODLE_DB_PASSWORD '' \
    MOODLE_DB_USER '' \
    MOODLE_DB_NAME '' \
    MOODLE_DB_PORT '3306'

# Installing php and external tools
RUN apt-get update && \
		apt-get -f -y install --no-install-recommends rsync unzip netcat libxmlrpc-c++8-dev libxml2-dev libpng-dev libicu-dev libmcrypt-dev &&\
 		docker-php-ext-install xmlrpc && \
		docker-php-ext-install mbstring && \
		docker-php-ext-install zip && \
		docker-php-ext-install xml && \
		docker-php-ext-install intl && \
 		docker-php-ext-install soap && \
 		docker-php-ext-install mcrypt && \
		docker-php-ext-install gd && \
		docker-php-ext-install opcache && \
		echo "Installing moodle" && \
		curl https://download.moodle.org/download.php/direct/stable${VERSION}/moodle-latest-${VERSION}.zip -o /tmp/moodle-latest.zip  && \
		rm -rf /var/www/html/index.html && \
		cd /tmp &&	unzip /tmp/moodle-latest.zip && cd / \
		mkdir -p /usr/src/moodle && \
		mv /tmp/moodle /usr/src/ && \
		chown www-data:www-data -R /usr/src/moodle && \
		apt-get purge -y unzip &&\
		apt-get autoremove -y &&\
		apt-get autoclean &&\
		rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* cache/* /var/lib/log/*

# Install Redis 4.1 support
RUN pecl install redis-4.1.1 \
    && docker-php-ext-enable redis

# Install Memcached support
RUN apt-get update \
    && apt-get install -y libmemcached-dev unzip git-core \
    && yes yes | pecl install memcached \
    && docker-php-ext-enable memcached \
    && apt-get clean && rm -rf /var/lib/apt/lists* /tmp/* /var/tmp/*

# Install MooSh
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    /usr/local/bin/composer self-update && \
    git clone git://github.com/tmuras/moosh.git /usr/local/moosh-online && \
    cd /usr/local/moosh-online && composer install && \
    ln -s /usr/local/moosh-online/moosh.php /usr/local/bin/moosh

COPY ./scripts/moodle-config.php /usr/src/moodle/config.php
